"""resume

Revision ID: 2334f78388b9
Revises: b08ef211891a
Create Date: 2018-07-28 13:05:33.738994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2334f78388b9'
down_revision = 'b08ef211891a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('year', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('sub_title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.String(length=800), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_category'), 'resume', ['category'], unique=False)
    op.create_index(op.f('ix_resume_sub_title'), 'resume', ['sub_title'], unique=False)
    op.create_index(op.f('ix_resume_timestamp'), 'resume', ['timestamp'], unique=False)
    op.create_index(op.f('ix_resume_title'), 'resume', ['title'], unique=False)
    op.create_index(op.f('ix_resume_year'), 'resume', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_year'), table_name='resume')
    op.drop_index(op.f('ix_resume_title'), table_name='resume')
    op.drop_index(op.f('ix_resume_timestamp'), table_name='resume')
    op.drop_index(op.f('ix_resume_sub_title'), table_name='resume')
    op.drop_index(op.f('ix_resume_category'), table_name='resume')
    op.drop_table('resume')
    # ### end Alembic commands ###
